title = "Topics Definition"

[topics]
    [topics.imu]
        server = "127.0.0.1"
        port = "5001"
        message_type = "ImuMsg"
    [topics.encoders]
        server = "127.0.0.1"
        port = "5002"
        message_type = "JointSensorsMsg"
    [topics.commands]
        server = "127.0.0.1"
        port = "5003"
        message_type = "MotorCmdMsg"
    [topics.ekf]
        server = "127.0.0.1"
        port = "5004"
        message_type = "EKFMsg"