title = "Topics Definition"

[topics]
    [topics.imu]
        server = "192.168.3.123"
        port = "5001"
        message_type = "ImuMsg"
    [topics.encoders]
        server = "192.168.3.123"
        port = "5002"
        message_type = "JointSensorsMsg"
    [topics.commands]
        server = "192.168.3.123"
        port = "5003"
        message_type = "MotorCmdMsg"
    [topics.ekf]
        server = "192.168.3.123"
        port = "5004"
        message_type = "LeggedEKFMsg"
    [topics.vicon]
        server = "192.168.3.123"
        port = "5000"
        message_type = "ViconMsg" 
        